config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  resources :pages

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  validates_uniqueness_of :slug, :title
  validates_format_of     :slug, with: /\A[a-z]+\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

  def show
    if params[:id].to_i == 0
      @page = Page.find_by_slug(params[:id])
    else
      @page = Page.find(params[:id])
    end
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new
    @page.slug = params[:page][:slug]
    @page.title = params[:page][:title]
    @page.content = params[:page][:content]

    if @page.save
      flash.notice = 'Saved'
      redirect_to pages_url
    else
      flash.now[:error] = 'Could not save'
      render :new
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    @page.slug = params[:page][:slug]
    @page.title = params[:page][:title]
    @page.content = params[:page][:content]

    if @page.save
      flash.notice = 'Saved'
      redirect_to "/pages/#{@page.id}"
    else
      flash.now[:error] = 'Could not save'
      render :edit
    end
  end

  def destroy
    flash.notice = 'Page deleted'
    @page = Page.find(params[:id])
    @page.destroy
    redirect_to pages_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiny CMS</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |name, msg| -%>
      <% if name == 'error' %>
        <div class='error flash'>
          <%= msg %>:
          <ul>
          <% @page.errors.full_messages.each do |error_msg| %>
            <li><%= error_msg %></li>
          <% end -%>
          </ul>
        </div>
      <% else -%>
        <%= content_tag :div, msg, class: 'notice flash' %>
      <% end -%>
    <% end -%>

    <%= yield %>
    <br>
    <footer>
      <%= link_to 'Home', root_path unless request.path == '/'   %>
    </footer>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Edit Page</h1>

<%= form_for @page do |f| %>
  <p>
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pages/index.html.erb
<h1>Pages</h1>

<p>
  <%= link_to 'New Page', new_page_path %>
</p>

<ul>
  <% Page.all.each do |page| %>
    <li>
      <%= link_to page.title, page_path(page.slug) %> |
      <%= link_to 'Edit', edit_page_path(page) %> |
      <%= link_to 'Delete',  page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= form_for @page do |f| %>
  <p>
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<div><%= @page.content %></div>